Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"

  # =========================
  # SERVER
  # =========================
  config.vm.define "alprivalS" do |server|
    server.vm.hostname = "alprivalS"

    server.vm.network "private_network",
      ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "alprivalS"
      vb.memory = 2048
      vb.cpus = 2
    end

    server.vm.provision "shell",
      path: "scripts/install_k3s_server.sh"
  end

  # =========================
  # SERVER WORKER
  # =========================
  config.vm.define "alprivalSW" do |worker|
    worker.vm.hostname = "alprivalSW"

    worker.vm.network "private_network",
      ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "alprivalSW"
      vb.memory = 2048
      vb.cpus = 2
    end

    worker.vm.provision "shell",
      path: "scripts/install_k3s_agent.sh"
  end

end